[2019-10-01 23:21:18,662] - [get_word_list_by_process.py:57] - [ERROR] - [[Errno 61] Connection refused]
[2019-10-11 17:54:28,775] - [log_manual.py:50] - [INFO] - [this is a info log]
[2019-10-11 17:54:28,775] - [log_manual.py:51] - [ERROR] - [this is a error log]
[2019-10-14 11:15:25,498] - [pandas_manual.py:187] - [ERROR] - ['utf-8' codec can't decode byte 0xd6 in position 0: invalid continuation byte]
[2019-10-14 11:15:59,755] - [pandas_manual.py:187] - [ERROR] - ['utf-8' codec can't decode byte 0xd6 in position 0: invalid continuation byte]
[2019-10-14 11:16:20,853] - [pandas_manual.py:187] - [ERROR] - ['utf-8' codec can't decode byte 0xd6 in position 0: invalid continuation byte]
[2019-10-14 11:16:49,923] - [pandas_manual.py:188] - [ERROR] - ['utf-8' codec can't decode byte 0xd6 in position 0: invalid continuation byte]
[2019-10-14 11:17:33,875] - [pandas_manual.py:188] - [ERROR] - ['utf-8' codec can't decode byte 0xd6 in position 0: invalid continuation byte]
[2019-10-14 11:17:54,502] - [pandas_manual.py:188] - [ERROR] - ['utf-8' codec can't decode byte 0xd6 in position 0: invalid continuation byte]
[2019-10-14 11:19:10,451] - [pandas_manual.py:187] - [ERROR] - ['utf-8' codec can't decode byte 0xd6 in position 0: invalid continuation byte]
[2019-10-14 11:19:44,092] - [pandas_manual.py:187] - [ERROR] - ['utf-8' codec can't decode byte 0xd6 in position 0: invalid continuation byte]
[2019-10-14 11:19:54,794] - [pandas_manual.py:187] - [ERROR] - ['utf-8' codec can't decode byte 0xd6 in position 0: invalid continuation byte]
